[package]
name = "std"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true

[dependencies]
lazy_static = { "version" = "1.0", "features" = ["spin_no_std"] }
good_memory_allocator = "0.1.7"
hashbrown = "0.13.1"
spin = "0.5.2"
